### ISSUE TITLE
Wrong repository contents on custom branch

### ISSUE THREAD

**Issue by nfgrilo** [askthecode/documentation#16]
I'm getting the wrong repository contents (from other repository, not mine) when using the plugin on a branch: the listed files are not part of my repository.

Things to note:
- using custom branch
- tested with sha-commit and branch name on the url as per docs
- using private repository

<img width="878" alt="Screenshot 2023-10-19 at 19 27 33" src="https://github.com/askthecode/documentation/assets/2744944/2ca07458-6474-475d-ba2a-52bc67b78cca">

<img width="852" alt="Screenshot 2023-10-19 at 19 30 46" src="https://github.com/askthecode/documentation/assets/2744944/88a1811a-2ba3-491c-ba6f-f620adb9b2eb">

**Comment by dsomok** [comment]
Hi @nfgrilo,

It seems that the files ChatGPT printed are likely a result of a model hallucination. Specifically, it included common files such as `.gitignore`, `LICENSE`, and `README`, added a Python file with the name of the repository, a test file, and a typical `requirements.txt` with a list of dependencies.

These hallucinations often occur due to the GPT model's context overflow.

Could you please check the actual response from the plugin? Specifically, does it contain any files at all? If it does, could you let me know the total character count of the response? I've observed that after the latest model updates, hallucinations tend to occur when the plugin response is larger than approximately 25k characters.

**Comment by nfgrilo** [comment]
Hey @dsomok,

The files on the response are actually the right ones!... but, indeed, the response has ~30k characters...

<img width="737" alt="image" src="https://github.com/askthecode/documentation/assets/2744944/adc4936d-8540-4acf-aea6-f00a8baf2713">

**Comment by dsomok** [comment]
Unfortunately, this is a known issue, and I am working on a fix for it. I plan to release a new version which will contain fixes for such issues this weekend.

There's a related issue concerning file contents analysis, which you can find here: [#9](https://github.com/askthecode/documentation/issues/9).

The reduction in capacity has been observed with the latest model deployments to ChatGPT. In the upcoming version, I'll adjust the endpoint to handle this reduced capacity more appropriately. However, this means that for prompts like "List all files" for large repositories, the initial response will likely list only the directories of the repository. Subsequently, ChatGPT may ask you to specify which directories you'd like to list files for or provide similar prompts.

@nfgrilo, would such behavior be suitable for you?

Thank you for your understanding and patience.

**Comment by nfgrilo** [comment]
Looks like a clever way to circumvent the API limitations! Sounds good @dsomok !

**Comment by dsomok** [comment]
Hi @nfgrilo,

The new version has been released which should work better with large repositories. Could you please test it on your end and let me know if the issue was fixed or not?

**Comment by nfgrilo** [comment]
It's working great @dsomok !
I'm able to browse other branch (and files are properly listed/identified), and selectively ask for analysis/etc without any issue.

Thanks for the prompt response! 💪

**Comment by dsomok** [comment]
@nfgrilo, thanks for the confirmation! Super happy it's all working smoothly now.

I'm gonna close this issue, but if anything pops up, feel free to open a new one. Thanks for the feedback! :)
