### ISSUE TITLE
It seems like there was an issue with processing your request

### ISSUE THREAD

**Issue by IntiMech** [askthecode/documentation#17]
Hey there,

For the last 48 hours, I have not been able to get the plugin to access any repo. I have upgraded to a paid plan. I have also tried other plugins and also the Advanced data analysis mode of GPT Plus to make sure it was not GPT.

Here is the only output I get when I ask it to access any repo.

It seems like there was an issue with processing your request. Let's try again.
I apologize for the inconvenience. It seems like there is a technical issue with processing the request to check your repository.

**Comment by dsomok** [comment]
Hi @IntiMech,

I'm sorry for the inconvenience you're experiencing with the plugin. To help me better understand and address the issue, could you please share a sample conversation with me?

You can easily share the conversation using the "Share" functionality of ChatGPT, located at the top-right corner of the chat.

**Comment by Pemh** [comment]
I have the same problem, I can't access any repo with the plugin. Here is a sample conversation with askthecode:
https://chat.openai.com/share/5371d480-507f-4464-b97b-227725d5c21e

**Comment by dsomok** [comment]
@Pemh Thanks for sharing the conversation, it helped a lot!

I've tried to press the **"Continue this conversation"** button and simply regenerate the response to see the error it throws:
![image](https://github.com/askthecode/documentation/assets/2426834/dedae7c5-0650-4a58-bcd4-9843ebeffb87)

So, the request actually never reaches the plugin, which also explains why I cannot see any errors in the logs.
I've seen mentions of this error on the OpenAI Forum:
https://community.openai.com/t/issues-with-using-plugins-in-chatgpt-4-since-october-21-2023/445873

Here, users describe that ChatGPT plugins stopped working for them (please note that this thread is not related to the AskTheCode plugin but rather to the plugin functionality in general).

According to the latest message, it's possible that the problem has been fixed. Could you please check it once again and ping me if it succeeds or not?

@IntiMech I believe that it's possible that you've experienced the same issue, could you please test if it works for you once again?

**Comment by dsomok** [comment]
hi @IntiMech, thank you for your feedback! I'm glad to hear that the issue has been resolved, hopefully forever :)

@Pemh, could you please try using the plugin once again and let me know if everything is working fine for you?

**Comment by Pemh** [comment]
hi @dsomok, I tried again and it works fine now.

**Comment by dsomok** [comment]
hi @Pemh, great, thanks for pinging me back
