### ISSUE TITLE
No option to cancel

### ISSUE THREAD

**Issue by EwanValentine** [askthecode/documentation#23]
I only needed to use this for a couple of months, but I don't seem to have a way to cancel this?

**Comment by dsomok** [comment]
Hi @EwanValentine

You can cancel your subscription by visiting the portal here:

https://c7d59216ee8ec59bda5e51ffc17a994d.auth.portal-pluginlab.ai/pricing


You can find more info on how to do it in the docs here:

https://docs.askthecode.ai/authentication/

**Comment by EwanValentine** [comment]
Got it, thanks!

**Comment by kumanday** [comment]
I keep getting charges but when I log in it says I am on the free plan

**Comment by dsomok** [comment]
Hi @encryptedcommerce, sorry for the inconvenience with your payments.

The reason why it says that you are on the free plan is most likely due to the fact that you log in with different account than the one with the subscription.

Could you please reach out to me via my email dsomok.github@gmail.com with the details regarding your last payment (date, last 4 digits), so I could find your subscription. Also, I will do all appropriate refunds for you.

**Comment by kumanday** [comment]
Thank you for your response and kind attention in resolving the issue.

**Comment by TylorS** [comment]
What about now? The login link doesn't work above anymore
