### ISSUE TITLE
Why are you asking for so many permissions on GitHub?

### ISSUE THREAD

**Issue by StevenTCramer** [askthecode/documentation#3]
![image](https://github.com/askthecode/askthecode.github.io/assets/357219/2450d28f-0abb-4fcf-afbe-3b1926ec2ce7)

**Comment by dsomok** [comment]
Hello @StevenTCramer,

Thank you for raising an issue. I acknowledge that requiring admin permission for "Repository webhooks and services" is an oversight on my part. I apologize for the inconvenience and will address this in the next release.

As for requesting access to private repositories, it is an intended behavior. This allows users to communicate with the code in their private repositories using the AskTheCode plugin. I want to assure you that AskTheCode does not collect or store the contents of the files, neither in any storage nor in logs. The AskTheCode plugin acts purely as a proxy to download the content and send it to ChatGPT for processing.

I apologize for the delay in my response. I wanted the Issues feature to be implemented enough to be able to reply.

> **Note:** This reply was generated by the Github Issues feature of the AskTheCode plugin. This feature is currently in development and will be released soon.

**Comment by Zure1** [comment]
A lot of those permissions seem to be unnecessary. Anything else than 'Code' should not be interesting for the plugin. In addition, why does it need **write** permissions?

![Bildschirmfoto 2023-09-04 um 09 55 11](https://github.com/askthecode/askthecode.github.io/assets/22812225/023115c9-71eb-4572-80da-472527fc3526)

**Comment by Zure1** [comment]
As far as I understand, it only downloads the code and sends it to ChatGPT, so reading issues seems pointless as of now.

**Comment by dsomok** [comment]
Hello everyone,

Thank you for your feedback and concerns regarding the permissions requested by the AskTheCode plugin. The primary goal is to allow users to query both public and private repositories.

Currently, the OAuth app (not the GitHub App) is used to authenticate users. Due to GitHub's current OAuth permission model, to access private repositories, I need to request the `repo` scope. This scope, unfortunately, grants full control of private repositories, which includes both read and write access. As of now, GitHub does not provide a separate read-only scope for private repositories. This means that even though the intention is only to read from your repositories, the permission model makes it appear as if the plugin is requesting broader access.

For more details on GitHub OAuth scopes, you can refer to the [official documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes).

**Comment by Zure1** [comment]
That's a quite sad limitation. Thanks for clarifying!
